// kitchen-sink/vue/src/pages/home.vue
<template>
  <f7-page class="page-home">
    <f7-navbar large transparent md-center-title>
      <f7-nav-left>
        <f7-link panel-open="left" icon-ios="f7:menu" icon-md="material:menu"></f7-link>
      </f7-nav-left>
      <f7-nav-title>Framework7 Vue</f7-nav-title>
      <f7-nav-right>
        <f7-link
          class="searchbar-enable"
          data-searchbar=".searchbar-components"
          icon-ios="f7:search"
          icon-md="material:search"
        ></f7-link>
      </f7-nav-right>
      <f7-nav-title-large>Framework7 Vue</f7-nav-title-large>
      <f7-searchbar
        class="searchbar-components"
        search-container=".components-list"
        search-in="a"
        expandable
      ></f7-searchbar>
    </f7-navbar>

    <f7-list strong inset dividers-ios class="searchbar-hide-on-search">
      <f7-list-item title="About Framework7" link="/about/">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
    </f7-list>

    <f7-block-title class="searchbar-found">Components</f7-block-title>
    <f7-list strong inset dividers-ios class="components-list searchbar-found">
      <f7-list-item link="/accordion/" title="Accordion">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/action-sheet/" title="Action Sheet">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/area-chart/" title="Area Chart">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/autocomplete/" title="Autocomplete">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/badge/" title="Badge">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/breadcrumbs/" title="Breadcrumbs">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/buttons/" title="Buttons">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/calendar/" title="Calendar / Date Picker">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/cards/" title="Cards">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/cards-expandable/" title="Cards Expandable">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/checkbox/" title="Checkbox">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/chips/" title="Chips/Tags">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/color-picker/" title="Color Picker">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/contacts-list/" title="Contacts List">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/content-block/" title="Content Block">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/data-table/" title="Data Table">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/dialog/" title="Dialog">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/fab/" title="FAB">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/fab-morph/" title="FAB Morph">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/form-storage/" title="Form Storage">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/gauge/" title="Gauge">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/grid/" title="Grid / Layout Grid">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/icons/" title="Icons">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/infinite-scroll/" title="Infinite Scroll">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/inputs/" title="Inputs">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/list-button/" title="List Button">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/list/" title="List View">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/list-index/" title="List Index">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/login-screen/" title="Login Screen">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/menu-list/" title="Menu List">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/messages/" title="Messages">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/navbar/" title="Navbar">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/notifications/" title="Notifications">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/panel/" title="Panel / Side Panels">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/photo-browser/" title="Photo Browser">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/picker/" title="Picker">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/pie-chart/" title="Pie Chart">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/popover/" title="Popover">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/popup/" title="Popup">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/preloader/" title="Preloader">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/progressbar/" title="Progress Bar">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/pull-to-refresh/" title="Pull To Refresh">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/radio/" title="Radio">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/range/" title="Range Slider">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/searchbar/" title="Searchbar">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/searchbar-expandable/" title="Searchbar Expandable">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/segmented/" title="Segmented">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/sheet-modal/" title="Sheet Modal">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/smart-select/" title="Smart Select">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/sortable/" title="Sortable List">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/stepper/" title="Stepper">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/subnavbar/" title="Subnavbar">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/swipeout/" title="Swipeout (Swipe To Delete)">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/swiper/" title="Swiper Slider">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/tabs/" title="Tabs">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/text-editor/" title="Text Editor">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/timeline/" title="Timeline">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/toast/" title="Toast">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/toggle/" title="Toggle">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/toolbar-tabbar/" title="Toolbar & Tabbar">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/tooltip/" title="Tooltip">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/treeview/" title="Treeview">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
      <f7-list-item link="/virtual-list/" title="Virtual List">
        <template #media>
          <f7-icon icon="icon-f7" />
        </template>
      </f7-list-item>
    </f7-list>
    <f7-list strong inset dividers-ios class="searchbar-not-found">
      <f7-list-item title="Nothing found" />
    </f7-list>
    <f7-block-title class="searchbar-hide-on-search">Themes</f7-block-title>
    <f7-list strong inset dividers-ios class="searchbar-hide-on-search">
      <f7-list-item title="iOS Theme" external link="./?theme=ios" />
      <f7-list-item title="Material (MD) Theme" external link="./?theme=md" />
      <f7-list-item title="Color Themes" link="/color-themes/" />
    </f7-list>

    <f7-block-title class="searchbar-hide-on-search">Page Loaders & Router</f7-block-title>
    <f7-list strong inset dividers-ios class="searchbar-hide-on-search">
      <f7-list-item title="Page Transitions" link="/page-transitions/" />
      <f7-list-item title="Routable Modals" link="/routable-modals/" />
      <f7-list-item title="Default Route (404)" link="/load-something-that-doesnt-exist/" />
      <f7-list-item title="Master-Detail (Split View)" link="/master-detail/" />
      <f7-list-item title="Store" link="/store/" />
    </f7-list>
  </f7-page>
</template>
<script>
import {
  f7Page,
  f7Navbar,
  f7NavLeft,
  f7NavTitle,
  f7NavTitleLarge,
  f7NavRight,
  f7BlockTitle,
  f7List,
  f7ListItem,
  f7Link,
  f7Searchbar,
  f7Icon,
  theme,
} from 'framework7-vue';

export default {
  components: {
    f7Page,
    f7Navbar,
    f7NavLeft,
    f7NavTitle,
    f7NavTitleLarge,
    f7NavRight,
    f7BlockTitle,
    f7List,
    f7ListItem,
    f7Link,
    f7Searchbar,
    f7Icon,
  },
  props: {
    f7router: Object,
  },
  // eslint-disable-next-line
  setup() {
    return {
      theme,
    };
  },
};
</script>

// kitchen-sink/react/src/pages/home.jsx
import React from 'react';
import {
  Page,
  Navbar,
  NavLeft,
  NavTitle,
  NavTitleLarge,
  NavRight,
  BlockTitle,
  List,
  ListItem,
  Link,
  Searchbar,
  Icon,
} from 'framework7-react';

export default () => {
  return (
    <Page className="page-home">
      <Navbar large transparent mdCenterTitle>
        <NavLeft>
          <Link panelOpen="left" iconIos="f7:menu" iconMd="material:menu" />
        </NavLeft>
        <NavTitle>Framework7 React</NavTitle>
        <NavRight>
          <Link
            searchbarEnable=".searchbar-components"
            iconIos="f7:search"
            iconMd="material:search"
          />
        </NavRight>
        <NavTitleLarge>Framework7 React</NavTitleLarge>
        <Searchbar
          className="searchbar-components"
          searchContainer=".components-list"
          searchIn="a"
          expandable
        />
      </Navbar>

      <List strong inset dividersIos className="searchbar-hide-on-search">
        <ListItem title="About Framework7" link="/about/">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
      </List>

      <BlockTitle className="searchbar-found">Components</BlockTitle>
      <List strong inset dividersIos className="components-list searchbar-found">
        <ListItem link="/accordion/" title="Accordion">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/action-sheet/" title="Action Sheet">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/area-chart/" title="Area Chart">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/autocomplete/" title="Autocomplete">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/badge/" title="Badge">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/breadcrumbs/" title="Breadcrumbs">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/buttons/" title="Buttons">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/calendar/" title="Calendar / Date Picker">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/cards/" title="Cards">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/cards-expandable/" title="Cards Expandable">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/checkbox/" title="Checkbox">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/chips/" title="Chips/Tags">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/color-picker/" title="Color Picker">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/contacts-list/" title="Contacts List">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/content-block/" title="Content Block">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/data-table/" title="Data Table">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/dialog/" title="Dialog">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/fab/" title="FAB">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/fab-morph/" title="FAB Morph">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/form-storage/" title="Form Storage">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/gauge/" title="Gauge">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/grid/" title="Grid / Layout Grid">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/icons/" title="Icons">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/infinite-scroll/" title="Infinite Scroll">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/inputs/" title="Inputs">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/list-button/" title="List Button">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/list/" title="List View">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/list-index/" title="List Index">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/login-screen/" title="Login Screen">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/menu-list/" title="Menu List">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/messages/" title="Messages">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/navbar/" title="Navbar">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/notifications/" title="Notifications">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/panel/" title="Panel / Side Panels">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/photo-browser/" title="Photo Browser">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/picker/" title="Picker">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/pie-chart/" title="Pie Chart">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/popover/" title="Popover">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/popup/" title="Popup">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/preloader/" title="Preloader">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/progressbar/" title="Progress Bar">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/pull-to-refresh/" title="Pull To Refresh">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/radio/" title="Radio">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/range/" title="Range Slider">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/searchbar/" title="Searchbar">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/searchbar-expandable/" title="Searchbar Expandable">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/segmented/" title="Segmented">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/sheet-modal/" title="Sheet Modal">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/smart-select/" title="Smart Select">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/sortable/" title="Sortable List">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/stepper/" title="Stepper">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/subnavbar/" title="Subnavbar">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/swipeout/" title="Swipeout (Swipe To Delete)">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/swiper/" title="Swiper Slider">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/tabs/" title="Tabs">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/text-editor/" title="Text Editor">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/timeline/" title="Timeline">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/toast/" title="Toast">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/toggle/" title="Toggle">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/toolbar-tabbar/" title="Toolbar & Tabbar">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/tooltip/" title="Tooltip">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/treeview/" title="Treeview">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
        <ListItem link="/virtual-list/" title="Virtual List">
          <Icon slot="media" icon="icon-f7" />
        </ListItem>
      </List>
      <List strong inset dividersIos className="searchbar-not-found">
        <ListItem title="Nothing found" />
      </List>
      <BlockTitle className="searchbar-hide-on-search">Themes</BlockTitle>
      <List strong inset dividersIos className="searchbar-hide-on-search">
        <ListItem title="iOS Theme" external link="./?theme=ios" />
        <ListItem title="Material (MD) Theme" external link="./?theme=md" />
        <ListItem title="Color Themes" link="/color-themes/" />
      </List>
      <BlockTitle className="searchbar-hide-on-search">Page Loaders & Router</BlockTitle>
      <List strong inset dividersIos className="searchbar-hide-on-search">
        <ListItem title="Page Transitions" link="/page-transitions/" />
        <ListItem title="Routable Modals" link="/routable-modals/" />
        <ListItem title="Default Route (404)" link="/load-something-that-doesnt-exist/" />
        <ListItem title="Master-Detail (Split View)" link="/master-detail/" />
        <ListItem title="Store" link="/store/" />
      </List>
    </Page>
  );
};
